version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn oj.wsgi:application --config gunicorn.conf.py
    volumes:
      - static_volume:/code/staticfiles
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - static_volume:/code/staticfiles
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  redis:
    image: redis:alpine
    container_name: redis_server

  celery:
    build: .
    command: ./celery-start.sh
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - web

volumes:
  static_volume:
