version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn oj.wsgi:application --config gunicorn.conf.py
    volumes:
      - static_volume:/code/staticfiles
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis_server

  celery:
    build: .
    container_name: oj_celery_worker
    command: ["sh", "celery-start.sh"]
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - web

volumes:
  static_volume:
